name = "image-registry-proxy"
main = "src/index.js"
compatibility_date = "2025-02-21"

minify = true

workers_dev = false
preview_urls = false

[dev]
ip = "0.0.0.0"
port = 8787

[vars]
Target = "https://registry-1.docker.io"
DisableProxyAuth = false
DisablePrefixRoute = false
