name = "image-registry-proxy"
main = "src/index.js"
compatibility_date = "2025-02-21"

[vars]
Target = ""
DisableProxyAuth = false
DisablePrefixRoute = false

[env.production]
minify = true

[env.production.vars]
Target = "https://registry-1.docker.io"
